name: Maven CI

on:
  workflow_call:
    inputs:
      java-version:
        required: false
        type: string
        default: '17'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Fetch all history for accurate versioning

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: ${{ inputs.java-version }}
          distribution: 'temurin'
       
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v1
        with:
          versionSpec: '6.0.x'

      - name: Run GitVersion
        id: gitversion
        uses: gittools/actions/gitversion/execute@v1

      - name: Show calculated version
        run: echo "Build version: ${{ steps.gitversion.outputs.semVer }}"

      - name: Set Maven version
        run: mvn versions:set -DnewVersion=${{ steps.gitversion.outputs.semVer }}

      - name: Add Maven version to workflow summary
        run: |
          mvn -q -Dexec.executable="echo" -Dexec.args='${project.version}' --non-recursive exec:exec > mvn_version.txt
          echo "### Maven Project Version: $(cat mvn_version.txt)" >> $GITHUB_STEP_SUMMARY

      - name: Build with Maven
        run: mvn clean install

      - name: Run tests
        run: mvn test

      - name: Package application
        run: mvn package

      - name: Upload JAR file
        uses: actions/upload-artifact@v4
        with:
          name: maven-artifact.jar
          path: target/*.jar

      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: target/surefire-reports/

      - name: Notify build status
        run: echo "Build completed successfully!"name: Maven CI

on:
  push:
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Fetch all history for accurate versioning

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
       
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v1
        with:
          versionSpec: '6.0.x'  # Specify the version of GitVersion you want to use

      - name: Run GitVersion
        id: gitversion
        uses: gittools/actions/gitversion/execute@v1

      - name: Show calculated version
        run: |
            echo "Build version: ${{ steps.gitversion.outputs.semVer }}"

      - name: Set Maven version
        run: mvn versions:set -DnewVersion=${{ steps.gitversion.outputs.semVer }}

      - name: Add Maven version to workflow summary
        run: |
          mvn -q -Dexec.executable="echo" -Dexec.args='${project.version}' --non-recursive exec:exec > mvn_version.txt
          echo "### Maven Project Version: $(cat mvn_version.txt)" >> $GITHUB_STEP_SUMMARY

      - name: Build with Maven
        run: mvn clean install

      - name: Run tests
        run: mvn test

      - name: Package application
        run: mvn package

      - name: Upload JAR file
        uses: actions/upload-artifact@v4
        with:
          name: maven-artifact.jar
          path: target/*.jar

      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: target/surefire-reports/
          

      - name: Notify build status
        run: echo "Build completed successfully!"
        # You can replace this with a notification action or script if needed.
        # For example, you could use Slack, email, or any other notification service.
